# название вашего action
name: Semgrep

# условия выполнения action - при внесении изменений в ветки main и test
on:
  push:
    branches:
      - main
      - test

# содержание action - создание и выполнение контейнера с анализатором
jobs:
  semgrep:
    name: Semgrep CI
    runs-on: ubuntu-latest
    container:
      image: semgrep/semgrep
    env:
      SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run Semgrep
        run: semgrep ci
